cocli/data/templates/corim-full.json
This change corrects the corim-full.json template to only have one profile as multiple profiles are not permitted.
This addresses #65
=> Fix corim-full.json template to have only 1 profile

corim/signedcorim_test.go, corim/signer.go
Add support for ES384, ES512, EdDSA, PS256, PS384, and PS512, which are supported by the go-cose library but were not being exposed here.
This addresses https://github.com/veraison/corim/issues/57
=> Add support for missing go-cose signing algorithms

Makefile, README.md, cocli/cmd/comidCreate.go, cocli/cmd/comidCreate_test.go, cocli/cmd/comidValidate.go, cocli/cmd/common.go, cocli/cmd/corimCreate.go, cocli/cmd/corimDisplay.go, cocli/cmd/corimExtract.go, cocli/cmd/corimSign.go, cocli/cmd/corimSubmit_test.go, cocli/cmd/corimVerify.go, cocli/cmd/cotsCreate.go, cocli/cmd/test_vars.go, cocli/main.go, corim/cbor.go, corim/entity.go, corim/entity_test.go, corim/meta.go, corim/meta_test.go, corim/signedcorim.go, corim/unsignedcorim.go, corim/unsignedcorim_test.go, cots/cbor.go, cots/cots.go, cots/cots_test.go, cots/env_group.go, cots/env_group_test.go, cots/example_test.go, go.mod
Reverting module /v2 module name change. The reason is that go build system does not allow specifying a post-v1 module name unless there is a corresponding published release. Since we're not planning on publishing v2.0.0 until CoRIM spec is out of draft, we cannot rename the module until then. So for now, v2 development needs to happen on top of a v1 module name.
=> Partial v2 revert

comid/cbor.go, comid/integrityregisters.go, comid/integrityregisters_test.go, comid/measurement.go
This PR implements the recently added Integrity Registers (https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#name-integrity-registers) to the CoRIM schema.
Fixes #108
=> Add Integrity registers

comid/classid.go, comid/instance.go, comid/instance_test.go, comid/measurement.go, comid/measurement_test.go
As part of adding extension enhancement to `CoRIM`, part of the interfaces for CoMID library were omitted.
These are required and is been invoked from `veraison/services`.
=> Provide missing interface implementations

.github/workflows/ci.yml, cocli/README.md, cocli/cmd/corimSubmit.go, cocli/cmd/corimSubmit_test.go, cocli/cmd/isubmitter.go, go.mod, go.sum
- Add TLS upport
- Also fix macos-latest CI
=> Add TLS support

comid/classid.go, comid/entity.go, comid/flagsmap.go, comid/measurement.go, comid/triples.go, corim/entity.go, corim/meta.go
Use value, rather than pointer, receivers for MarshalCBOR and MarshalJSON methods. Since those methods don't mutate the structures, pointers are not necessary, and using them prevents the methods from being invoked when marshaling an instance of that structure (rather than a pointer to one). This is not a huge deal as CoRIM fields typically use pointers, however it can lead to surprising results when playing with the structures on their own.
=> fix: use value receivers for MarshalXXX methods

extensions/collection.go, extensions/collection_test.go
Fixs a couple of bugs in `extensions.Collection` Implementation
=> extensions.Collection fixes

cocli/cmd/root.go, go.mod, go.sum
Use ca_cert certs when configuring the OAuth2 authenticator, in addition to their current use in connection to the API service.
=> fix: propagate ca_cert to OAuth2 authenticator

README.md
Adds a “Required Tools” section to the [README.md](https://github.com/veraison/corim/blob/main/.github/workflows/linters.yml) specifying the exact versions of Go and golangci-lint needed to run the linter locally. This would ensure that developers install the apt versions, avoiding possible inconsistencies or incorrect linting errors as can be seen in https://github.com/veraison/corim/issues/146
=> Adds required tools section to README.md 

README.md, comid/svn.go, comid/svn_test.go
Refactors the SVN value conversion logic into a separate function to improve readability and maintainability. The newly created function handles the conversion of various types to for SVN.
Changes made :- 
A new function convertToSVNUint64() is created to handle the conversion of various types to uint64 for SVN. Existing functions in svn.go NewTaggedSVN() and NewTaggedMinSVN() have been refactored to use this newly created function convertToSVNUint64().
=> Refactor SVN Value Conversion Logic into a Separate Function

extensions/README.md
=> Docs: Improved Extension Points, Their Parent Structures, and Where You Call RegisterExtensions()

corim/example_profile_test.go, corim/profiles.go, corim/profiles_test.go, extensions/README.md
This pull request refactors the Profile struct to ProfileManifest across the codebase to resolve name collisions and improve code clarity.
Changes Made
Renamed the Profile struct to ProfileManifest in:
profiles.go
profiles_test.go
Related methods and variables.
Updated function signatures and internal references to align with the new struct name.
Ensured compatibility with all test cases, and verified that all tests pass successfully.
Why This Change Was Made
The previous implementation used the name Profile for both:
A variable representing eat.Profile (used as a ProfileID).
A struct that associates an eat.Profile with extensions.
This caused name collisions and confusion. Renaming the struct to ProfileManifest resolves these issues and aligns with naming conventions.
Testing
Ran the …
=> refactor(profiles): rename Profile to ProfileManifest and update related functions

comid/environment_test.go
The ToCBOR and FromCBOR have been changed to the following order:
Empty
Class only
Instance only
Group only
Class and Instance
Class and Group
Instance and Group
Class and Instance and Group
The missing tests have also been added.
=> comid/environment: improve ToCBOR and FromCBOR tests

comid/digests.go, comid/digests_test.go, comid/flagsmap.go, comid/flagsmap_test.go, comid/integrityregisters.go, comid/integrityregisters_test.go, comid/macaddr.go, comid/measurement.go, comid/rawvalue.go, comid/rawvalue_test.go, comid/svn.go, comid/svn_test.go, comid/version.go, comid/version_test.go
Adds a compare routine to some of the measurement types.
=> Add routines to compare measurements against reference

corim/signedcorim.go, corim/signedcorim_test.go
=> Updates the SignedCorim Sign method to include certificates

corim/signedcorim.go, corim/signedcorim_test.go
x5chain is of type `COSE_X509`, which is defined as:
COSE_X509 = bstr / [ 2*certs: bstr ]
If there is only one element, it should be encoded as a simple `bstr` instead of being represented as an array.
=> fix(corim): handle silly RFC9360 microoptimisation

corim/signedcorim.go, corim/signedcorim_test.go
If intermediate certificates are provided, the EE certificate must also be provided.
=> fix(corim): missing check when adding x5chain

comid/cbor.go, comid/rawint.go, comid/rawint_test.go
Add a raw int concrete type as mentioned in the IETF CoRIM spec: https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#name-raw-int
=> rawint: add a raw int concrete type

corim/unsignedcorim.go, corim/unsignedcorim_test.go
UnsignedCorim.FromCBOR() checks for the unsigned  corim tag by taking a slice of the first three bytes of the input. This will panic if the input is shorter than three bytes, so check for that first.
=> fix: handle short buffers inside UnsignedCorim.FromCBOR()

coev/coswid_evidence.go, coev/coswid_evidence_test.go, coev/coswidtriple.go, coev/example_test.go, coev/test_vars.go, cots/abbreviated_swid_evidence_test.go, cots/abbreviated_swid_tag.go, go.mod, go.sum
This PR implements Evidence validation in CoRIM using the newly added Valid() methods from the SWID package, completing the work requested in issue #212.
This implementation depends on the updated SWID package with Valid() methods from veraison/swid#23, which was completed via veraison/swid#45. The go.mod has been updated to use the SWID version containing these validation methods via replace directive.
*CoSWIDEvidenceMap.Valid()*
- Validates TagID field when present using TagID.Valid() method
- Validates Evidence field using swid.Evidence.Valid() method  
- Returns detailed error context for validation failures
*CoSWIDEvidence.Valid()*
- Validates all Evidence entries in the collection
- Provides specific error reporting with entry index for debugging
- Ensures at least one evidence …
=> Add Evidence validation using swid.Evidence.Valid() method
